### ISSUE TITLE
Make the delay for key rotation configurable

### ISSUE THREAD

**Issue by moritzheiber** [sam701/awstools#8]
Ideally I would be able to define a period of time after which a AWS access key is rotated by `awstools` instead of having it rotate it the key on every MFA (re)authentication since the process takes some time.

This will ease the pain of people with short MFA token lifetimes (i.e. < 24h or less).

**Comment by sam701** [comment]
@moritzheiber I agree, the solution you described is nicer. But it would require a persistent state between the tool invocation, in order to save `lastKeyRotationTime`.

The key rotation takes 1-2 seconds. One spends this time once a day if the MFA token lifetime is 12-24 hours. I found it acceptable for now. 

It is a valid enhancement though.

**Comment by moritzheiber** [comment]
Accrding to [the IAM API](http://docs.aws.amazon.com/IAM/latest/APIReference/API_AccessKeyMetadata.html) you don't need to store the state of the key you're currently using, you can just resolve the key lifetime dynamically.

We have a key lifetime of 4 hours over here, even just 60 minutes for other accounts with elevated privileges. I haven't enabled the feature yet, but this might become annoying over time ;)

How hard do you think this would be to implement?

**Comment by sam701** [comment]
It's awesome that the creation date of the access key can be retrieved from AWS. It could make the thing much easier. The solution would be introducing a new configuration option `keyRotationInterval` and check the key creation date before each role assumption. But I don't know much time it takes. It might take as much time as to rotate it without checking.

Another solution would be to save the creation time in a separate file (I have no clue now, where it can be, since linux and mac have different default directory policies). The interval checking can be done much faster in this case.

**Comment by moritzheiber** [comment]
🙌👍
